### ISSUE TITLE
Need little bit FIX

### ISSUE THREAD

**Issue by ffdown** [AlekPet/prompt_translate#1]
When I press the generate button or CTRL+ENTER it would be nice if the text entered into the translator, immediately loaded in the query field, and sometimes you enter text, but press the translation button and forgot, that is, in general, more automated translation would be. And by the way how to change the location on the screen? Because it is somehow very uncomfortable, between the query field and the negative query, it would be more logical, by the way it would not hurt to make two translation buttons to send one in the query, and the second in the negative query.

**Comment by AlekPet** [comment]
Hi. Tweaked the code a little, added a translation negative query. Also, auto-translation works, only when the script is enabled from below, otherwise the "run" method simply does not start, although after the translation, the translation text is not inserted into the field, I did not find a way to do it :).

**Comment by ffdown** [comment]
Что-то мы тут переводчиком зря балуемся, если все русскоязычные)) Заметил сегодня обнову, всё бы шикардос, но автоперевод не работает, при включении скрипта автоперевода вываливает такое:

"Traceback (most recent call last):
  File "E:\AI\SDPORT\modules\call_queue.py", line 56, in f
    res = list(func(*args, **kwargs))
  File "E:\AI\SDPORT\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "E:\AI\SDPORT\modules\txt2img.py", line 49, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "E:\AI\SDPORT\modules\scripts.py", line 337, in run
    processed = script.run(p, *script_args)
  File "E:\AI\SDPORT\modules\scripts.py", line 68, in run
    raise NotImplementedError()
NotImplementedError"

**Comment by ffdown** [comment]
А вот сегодня что-то в A1111 обновилось, теперь вовсе исчез плагин =( Переустановка не помогает.

**Comment by AlekPet** [comment]
Только, что проверил работает, теперь скрипт работает при выборе внизу в поле скриптов и перевод текста осуществляется прямо в Prompt и в Negative prompt, при нажатии соответствующих клавиш. Также доступен авто перевод если вы вбили текст в поле prompt, но забыли нажать на кнопку Translate, при условии, что стоит галочка Auto Translate. Старая версия тоже доступна тут https://github.com/AlekPet/prompt_translate/tree/Prompt-translate-(from_start_app)

**Comment by ffdown** [comment]
Сорян протупил, внизу если скрипт выбрать то да, всё на автомате переводится сразу при нажатии "generate" это прям каеф)) Прям топчиковое расширение, для тех кто на инглиш заморачиваться не любитель)) Пилите ещё полезненького)) За этот япрям благодарочка, кстати в поиске его что-то хрен найдёшь, хорошо что в закладки заныкал
