### ISSUE TITLE
Translating just in translate window

### ISSUE THREAD

**Issue by Rogal80** [AlekPet/prompt_translate#2]
Hi, is there any chance to translate just in the translation window and possibly have a button to send to prompt ?

**Comment by AlekPet** [comment]
I didn’t really understand that the translator window was separate and there was a button to insert into the query prompt? I changed the code a little, added the translation of the negative request and the translation of the text on the machine, if only the script is selected at the bottom in the scripts.

**Comment by Rogal80** [comment]
Ok, I get the point – but now after new update, using translate is blocking other script to use for example style pile, abg remover etc. -. Now the workflow is much slower than before :(

**Comment by AlekPet** [comment]
Here old version: https://github.com/AlekPet/prompt_translate/tree/Prompt-translate-(from_start_app)
